### ISSUE TITLE
运行vnpy mod报错，详细信息如下：

### ISSUE THREAD

**Issue by FallacyWalker** [ricequant/rqalpha-mod-vnpy#14]
log太长，发个文件：
[log20170420.txt](https://github.com/ricequant/rqalpha-mod-vnpy/files/939597/log20170420.txt)

**Comment by Cuizi7** [comment]
这个问题是由于 CTP 返回了未知的合约数据导致了 vnpy 报错，并非 vnpy mod 的问题。vnpy mod 即将在近期的重构中减少对 vnpy 的上层依赖，即可避免这个错误。

**Comment by Cuizi7** [comment]
这个问题在vnpy 的新版本代码中已经修复，请更新 vnpy 和 rqalpha-mod-vnpy。
