### ISSUE TITLE
在vnpy mod里，如何获得vnpy的交易数据呢 ？

### ISSUE THREAD

**Issue by FallacyWalker** [ricequant/rqalpha-mod-vnpy#16]

**Comment by Cuizi7** [comment]
vnpy mod 现已支持将 vnpy  的账户、持仓、订单、交易 等数据同步至 rqalpha ，可否具体描述一下您需要拿到何种数据？

**Comment by FallacyWalker** [comment]
目前需要获取行情，持仓，交易，委托，成交信息。

**Comment by Cuizi7** [comment]
行情数据暂时只能通过获取到快照数据，vnpy mod 尚未加入录入历史数据的功能。
持仓、交易、委托、成交均可通过在策略内执行 rqalpha 对应 API 获得。
