### ISSUE TITLE
初始化时获取重复获取open orders，仓位回复时候昨仓有误

### ISSUE THREAD

**Issue by handsomu** [ricequant/rqalpha-mod-vnpy#24]
对于仓位获取，注意上期所一个方向可能会返回两条仓位记录，一条昨仓，一条今仓。
由于YdPosition数据有误，所以使用Position获取当前总仓位，使用TodayPosition获取今仓，两者相减得到昨仓。

**Comment by Cuizi7** [comment]
master 分支已修复。
