### ISSUE TITLE
vnpy mod运行几分钟后，停止运行，弹出python.exe已停止工作的提示

### ISSUE THREAD

**Issue by FallacyWalker** [ricequant/rqalpha-mod-vnpy#4]
python version: 2.7.11
rqalpha version: 2.0.7
rqalpha_mod_vnpy version: 0.9.11
用pycharm运行；

**Comment by Cuizi7** [comment]
我暂时没有在windows平台上进行测试，晚一点测试了以后回来反馈。

**Comment by Cuizi7** [comment]
已更新新版本，如果您再在windows平台使用的话麻烦反馈一下使用结果，这个issue暂时关闭了。
