### ISSUE TITLE
程序初始化时获取不到某些合约的last_price导致portfolio有关计算出错

### ISSUE THREAD

**Issue by handsomu** [ricequant/rqalpha-mod-vnpy#8]
目前逻辑是在订阅市场行情 cache住，需要用到时候从里面获取。
但是不同品种期货交易时间不同，比如夜盘，就无法获取到股指期货的市场行情。
此时应当用持仓查询返回的昨结算价作为last_price

**Comment by Cuizi7** [comment]
在 develop 分支已经修复，采取的方法是在底层订阅所有的合约并缓存 snapshot，以保证能随时获取任意合约的 snapshot(last_price)。

**Comment by Cuizi7** [comment]
master 分支已更新。
